type.of.drug <- data.frame(Drug.Name = c("6-MAM*", "Caffeine","Erythritol",
                                         "etizolam", "Fent <5%","Fentanyl or Analog",
                                         "Heroin","Lactose","Mannitol", 
                                         "No Cuts", "No Library Match","Uncertain Carbohydrate",
                                         "Uncertain Match", "Sildenafil Citrate", "Acetaminophen",
                                         "Ascorbic Acid", "Cocaine Base","Dimethyl Sulfone",
                                         "Benzocaine","Glucose",  "Inositol",
                                         "MDMA","Microcrystalline Cellulose", "Noscapine",
                                         "Propionanilide","Sucrose","Uncertain Oil",
                                         "Xylazine","Xylitol", "AMB-FUBINACA", 
                                         "Methamphetamine", "Sugar Uncertain", "Heroin Base",
                                         "Benzodiazepine <5%", "Levamisole","Uncertain Salt",
                                         "Water", "3-FPM", "Diphenhydramine",
                                         "No Opioid", "No Cuts Caffeine", 
                                         "No Cuts Fent", "Oxycodone", "Cocaine",
                                         "Calcium Phosphate Dibasic", "4-ANPP", "Phenacetin",
                                         "DXM", "Plain flour", "Quinine",
                                         "Carmellose", "Acetoacetanilide", "Uncertain Oil/Carb/Sugar",
                                         "Taurine", "Cement", "No Cuts Methadone",
                                         "No Cuts Heroin", "Calcium Carbonate", "Ibuprofen",
                                         "Opium", "PEG","Sorbital",
                                         "Creatine", "Morphine","Wax",
                                         "Acetylsalicylic Acid", "Methadone","Tramadol",
                                         "Corn Syrup", "Cellulose", "Procaine",
                                         "Starch", "Lidocaine", "Plaster",
                                         "ACHMINACA", "Boric Acid", "Amphetamine",
                                         "Hydrocodone", "Oxymetholone", "Thiamine",
                                         "Talc", "Calcium Hydroxide","Polyethylene",
                                         "Codeine Sulfate", "doxycycline", "5F-ADB",
                                         "Sodium Bicarbonate", "Benzoquinone","Dextrose",
                                         "Glutamine", "Pantoprazole Sodium", "Codeine",
                                         "Albuterol sulfate","Citric Acid", "Gabapentin",
                                         "Sulfamethoxazole", "Sugar", "Sorbitol",
                                         "MDA", "Ketamine", "Etizolam"
                                         
                                         
),
Classification = c("Opioid", "Stimulant", "Buff",
                   "Benzodiazepine", "Opioid", "Opioid",
                   "Opioid", "Buff", "Buff",
                   "N/A", "N/A", "N/A",
                   "N/A", "Other", "Buff",
                   "Buff", "Stimulant", "Buff",
                   "Buff", "Buff", "Buff",
                   "Stimulant", "Buff", "Opioid", 
                   "Buff","Buff", "N/A", 
                   "Other", "Buff", "Synth Cannabinoid",
                   "Stimulant", "N/A", "Opioid",
                   "Benzodiazepine", "Buff", "N/A",
                   "N/A", "Stimulant", "Other",
                   "N/A", "N/A", 
                   "N/A", "Opioid", "Stimulant",
                   "Buff", "Precursor", "Buff",
                   "Other", "Buff", "Other",
                   "N/A", "Other", "N/A",
                   "Other", "Other", "Opioid",
                   "Opioid", "Buff", "Buff",
                   "Opioid", "Buff", "Buff",
                   "Other", "Opioid", "Other",
                   "Other", "Opioid", "Opioid",
                   "Buff", "Buff", "Buff", 
                   "Buff", "Buff", "Other",
                   "Synthetic Cannabinoid", "Other", "Stimulant",
                   "Opioid", "Other", "Other",
                   "Other", "Other", "Other",
                   "Opioid", "Other", "Synthetic Cannabinoid",
                   "Buff", "Other", "Buff",
                   "Buff", "Other", "Opioid",
                   "Other", "Buff", "Other",
                   "Other", "Buff", "Buff",
                   "Stimulant", "Other", "Benzodiazepine")
)


